### Updates an existing patient entity
PUT http://localhost:4000/patients/3c150d7d-2d60-4eb8-8610-296e415e8b3a
Content-Type: application/json

{
  "name": "John Doe UPDATED",
  "email": "john.doe22@example.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09"
}

###